CEB2-569 -Migration: License  RDS and dynamodb mapping
OUP/eac-microservices-core-platform pull request #26
Opened 2021-12-17 10:39 UTC by subbummani

## Description

Execute RDS stored procedure and extract all the erights Id and then map with corresponding OUP_Id.

## Links

https://oupagile.atlassian.net/browse/CEB2-569

## Solution description

  - change 1
  - change 2

## Checklist

  - [x] Self Reviewed
  - [ ] Feature Flagged
  - [ ] Executed the necessary unit and/or functional tests and all tests pass

## Screenshots / Timings

BEFORE:

---

AFTER:

---

2021-12-20 10:10 UTC, donuc-cg2 requested changes
The implementation looks good overall, but needs some refactoring

2021-12-20 10:10 UTC, donuc-cg2 commented on lambda-code/common/dbConnects.js
> +          console.log(`FAILED TO MAP ${erightsId}`);
Forgot about this. It should add the erightsId to the list of failed mappings, instead of simply logging it

2021-12-20 10:10 UTC, donuc-cg2 commented on lambda-code/license.js
> +    // const licenseIds = sqlResults.recordset.map(r => r.LICENSE_ID);
Comment no longer required

2021-12-20 10:10 UTC, donuc-cg2 commented on .vscode/settings.json
> +{
I am not that familiar with .vscode/. Do we really need this in the git tree? This looks like stuff that goes into .gitignore usually

2021-12-20 14:07 UTC, adrianPanainte1 commented on .vscode/settings.json
> +{
i agree, this can be removed

2021-12-20 14:35 UTC, adrianPanainte1 commented on lambda-code/common/dbConnects.js
> +function dynamoGetProductInfo(dynamo, erigthsID){
maybe since this is in common/dbConnects we could isolate the `product` related entities since they're not that common?

2021-12-21 09:14 UTC, subbummani commented on lambda-code/common/dbConnects.js
> +const dynamoClient = new AWS.DynamoDB({
set the region in env file

2021-12-21 10:46 UTC, adrianPanainte1 commented on lambda-code/common/extractOupId.js
> +    var i,j;
prefer let over var

2021-12-21 10:47 UTC, adrianPanainte1 commented on lambda-code/common/extractOupId.js
> +    for (i = 0,j = erightsIDs.length; i < j; i += pageSize) {
j is not necessary since it doesn't change

2021-12-21 10:48 UTC, adrianPanainte1 commented on lambda-code/license.js
> +    if(typeof event.offset === 'undefined'){
I would say all nullish values of offset would be invalid, not just undefined

2021-12-21 12:44 UTC, adrianPanainte1 approved these changes

2021-12-21 15:07 UTC, donuc-cg2 requested changes

2021-12-21 15:07 UTC, donuc-cg2 commented on lambda-code/common/extractOupId.js
> +    region: process.env.AWS_REGION,
a common function should not concern itself with the process global variable. Why not use a function and build the client in main? example:

```javascript
// common js file
const getDynamoClient = (region) => new AWS.DynamoDB({
   apiVersion: '2012-08-10'
   region,
  // etc.
})

// main
let dynamoClient;

main() {
  // [...]
  if(!dynamoClient){
    dynamoClient = getDynamoClient(process.env.AWS_REGION)
  }
  // [...]
}


```

2021-12-21 15:07 UTC, donuc-cg2 commented on lambda-code/common/extractOupId.js
> +    TableName: `OUP_ERIGHTS_ID_MAPPING_${process.env.EnvName}-primary`,
Same as above, we can use a factory as you did for dynamoGetOupIdInfo, and avoid binding process.env to the reusable code.

2021-12-21 16:05 UTC, subbummani commented on lambda-code/license.js
> +const {offset, limit} = event;
done

2021-12-21 16:05 UTC, subbummani commented on lambda-code/license.js
> +    sqlConnection = await sqlConnect({sqlConnection, sqlPool}, process.env);
done

2021-12-22 10:49 UTC, donuc-cg2 approved these changes

2021-12-22 10:49 UTC, merged